
import React from 'react';
import Instructions from '@/components/Instructions';

const TeamGeneratorInstructions = () => {
  return (
    <Instructions
      title="Team Generator Instructions"
      sections={[
        {
          title: "How to use the Team Generator",
          content: (
            <div className="space-y-3">
              <p>Follow these simple steps to create random teams:</p>
              <ol className="list-decimal list-inside space-y-2">
                <li>Enter names in the text box (one name per line) or upload a CSV file</li>
                <li>Select the number of teams you want to create</li>
                <li>Click the "Generate Teams" button</li>
                <li>View the generated teams with members distributed evenly</li>
              </ol>
              <p>You can reshuffle the teams any time by clicking the "Reshuffle Teams" button.</p>
            </div>
          )
        },
        {
          title: "CSV File Format",
          content: (
            <div className="space-y-3">
              <p>To import names via CSV, your file should:</p>
              <ul className="list-disc list-inside space-y-2">
                <li>Have one name per row (in the first column)</li>
                <li>Be plain text format</li>
                <li>Use commas as separators (if multiple columns exist)</li>
              </ul>
              <p>Example: John Smith,Team A,Other Info</p>
              <p>Note: Only the first column (name) will be used by the generator.</p>
            </div>
          )
        },
        {
          title: "About Random Team Generation",
          content: (
            <div className="space-y-3">
              <p>Our team generator:</p>
              <ul className="list-disc list-inside space-y-2">
                <li>Shuffles names using a fair randomization algorithm</li>
                <li>Distributes members across teams as evenly as possible</li>
                <li>Ensures no bias in team assignments</li>
              </ul>
              <p>Teams are generated by randomly assigning members in sequence, ensuring fair distribution even with uneven numbers.</p>
            </div>
          )
        },
        {
          title: "Use Cases",
          content: (
            <div className="space-y-3">
              <p>The Team Generator is perfect for:</p>
              <ul className="list-disc list-inside space-y-2">
                <li>Classroom group assignments</li>
                <li>Sports team selection</li>
                <li>Workshop breakout groups</li>
                <li>Party games and activities</li>
                <li>Office team-building exercises</li>
                <li>Project group assignments</li>
              </ul>
            </div>
          )
        }
      ]}
    />
  );
};

export default TeamGeneratorInstructions;
